name: Cucumber BDD
on: [push, pull_request]
jobs:
  bdd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npx playwright install --with-deps
      - name: Run Cucumber (Firefox)
        run: BROWSER=firefox npx cucumber-js
      - name: Upload BDD report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bdd-report
          path: bdd-report
